<?php

            return

            $tr = [
'str' => [
'0' => 'ULTIMELE ȘTIRI',
'1' => 'În direct ',
'2' => 'Știri',
'3' => 'Video',
'4' => 'Galerie foto',
'5' => 'Emisiuni',
'6' => 'Servicii',
'7' => 'Programe de televiziune',
'8' => 'Vârsta nu este un obstacol în viață! Cardiologul în vârstă de 109 ani a dezvăluit secretul longevității și sănătății sale excelente',
'9' => 'Reporterul nostru a reușit să intervieveze doctorul Rossi, care a explicat cum și-a prelungit viața curățându-și vasele de sânge.',
'10' => 'Arturo Rossi, un renumit cardiolog italian, s-a retras la 70 de ani, deși inima și corpul său au rămas tineri.',
'11' => 'Este pensionat de 39 de ani, dar nu stă o zi fără lucru!',
'12' => 'Academicianul are acum 109 ani, dar i se pare că are doar 60.',
'13' => 'La 109 ani, dr. Rossi a primit felicitări din partea președintelui Republicii. Fotografie de la locul de muncă al medicului.',
'14' => 'Dr. Rossi, ați spus de câteva ori că vasele de sânge curate este baza sănătății. Asta este adevărat?',
'15' => 'Totul este simplu. Funcționarea organelor și sistemelor organismului uman depinde de calitatea circulației sângelui, care furnizează oxigen și nutrienți organelor interne și, de asemenea, colectează dioxid de carbon și produse metabolice. În copilărie și tinerețe, ne mișcăm mai mult, vasele sunt noi, elastice și curate, iar organele au o nutriție maximă. Dar, odată cu vârsta, începem să ne mișcăm mai puțin, iar vasele noastre încep să se polueze. Acest lucru se datorează multor factori, nu numai nocivi (cum ar fi fumatul, alimentația nesănătoasă, mediul precar și un stil de viață sedentar), dar și naturale (cum ar fi depunerea de lipide, un proces care are loc în fiecare organism).',
'16' => 'Corpul uman îmbătrânește. Dacă acordați atenție și vă curățați vasele de sânge, veți avea ocazia să trăiți cel puțin 20 de ani mai mult, fără durere în organele și articulațiile interne, iar corpul dvs. va face minuni. Cu alte cuvinte, curățarea vaselor de sânge poate prelungi viața și sănătatea. Și aceasta nu este doar o teorie. Am recomandat această metodă pacienților mei și o practic personal. Toți cei care mi-au ascultat sfaturile și-au extins durata de viață.',
'17' => 'Acest grafic arată modul în care vasele de sânge sunt contaminate. Dacă nu le-ai curățat niciodată și ai peste 40 de ani, acestea conțin o mulțime de impurități. Acest lucru vă poate afecta sănătatea și este posibil ca procesul să fi început deja.',
'18' => 'Ce patologii pot provoca poluarea vaselor de sânge?',
'19' => 'După cum am spus - întregul corp suferă. Dar, în primul rând, acest lucru se aplică organelor și sistemelor direct legate de circulația sângelui, adică a sistemului cardiovascular.',
'20' => 'Poluarea în vasele de sânge poate declanșa următoarele boli',
'21' => 'Ateroscleroza',
'22' => 'Vasele sangvine nu mai funcționează bine: cele mici sunt complet blocate, iar cele principale conțin o mulțime de depozite de colesterol.',
'23' => 'Ischemie cardiacă',
'24' => 'Acest lucru este cauzat de lipsa de sânge în vasele coronare, care la rândul său se datorează impurităților prezente în vase.',
'25' => 'Accident vascular cerebral',
'26' => 'Întreruperea fluxului de sânge către creier duce la moartea terminațiilor nervoase, ceea ce duce la pierderea anumitor funcții.',
'27' => 'Hipertensiune',
'28' => 'Poluarea vaselor de sânge determină o îngustare a venelor și o creștere a tensiunii arteriale.',
'29' => 'Dilatatrea venelor varicoase',
'30' => 'Apare și în interiorul corpului și nu doar pe picioare (o problemă alarmantă pentru femei). Hemoroizii sunt o consecință a extinderii venelor.',
'31' => 'Tromboză venoasă și arterială',
'32' => 'Depozitele de impurități prezente în vasele de sânge provoacă cheaguri de sânge și moarte vasculară, ceea ce poate duce la moartea unui grup de celule din corp. Dacă cheagul de sânge se dizolvă și intră în fluxul sanguin, poate apărea blocarea vaselor de sânge ale inimii (stop cardiac), care în 70% din cazuri este însoțit de moartea pacientului.',
'33' => 'Următoarele fotografii arată pericolul pe care îl depun depozitele în celulele sanguine pentru sănătate și cât de mult reduc durata vieții.',
'34' => 'Inima unei femei care a murit în urma unui stop cardiac',
'35' => 'Bărbat de 53 de ani care a suferit un accident vascular cerebral. Un accident vascular cerebral duce la dizabilitate în toate cazurile, iar pacienții afectați au nevoie de îngrijiri speciale. Motivul este un blocaj al vaselor de sânge.',
'36' => 'Varicele, de care suferă multe femei, sunt, de asemenea, un rezultat direct al depunerilor în vase.',
'37' => 'Această problemă se răspândește. Boala cardiovasculară provoacă de patru ori mai multe decese decât alte cauze. Medicii știu acest lucru, ei știu că curățarea vaselor de sânge este necesară, dar din anumite motive neclare, medicina italiană ignoră acest aspect. Majoritatea medicilor prescriu medicamente pentru scăderea tensiunii arteriale, pentru hipertensiune arterială; cu toate acestea, acestea nu sunt destinate pentru a trata, ci au doar un efect temporar. Vasele de sânge trebuie curățate. Apropo, oamenii de peste 35-40 de ani practică această metodă de mai bine de jumătate de secol în Statele Unite și Europa, unde pacienții sunt conștienți de necesitatea de a curăța vasele de sânge.',
'38' => 'Există simptome care indică prezența depozitelor în vasele de sânge?',
'39' => 'Desigur ca da. Principalele simptome sunt',
'40' => 'Migrenele',
'41' => 'Memorie deteriorată',
'42' => 'Oboseala cronica',
'43' => 'Insomnie',
'44' => 'Probleme de potență',
'45' => 'Insuficiență vizuală și auditivă',
'46' => 'Tensiune ridicată',
'47' => 'Boli respiratorii și angină pectorală',
'48' => 'Pielea palidă a picioarelor',
'49' => 'Dureri musculare și articulare',
'50' => 'Indiferent dacă aveți sau nu unul dintre aceste simptome, după 30 de ani, trebuie să vă curățați vasele de sânge cel puțin o dată la 5 ani. Acest lucru vă va permite să aveți sănătate de fier.',
'51' => 'Vasele de sânge au capacitatea de a colecta impuritățile, în special la persoanele în vârstă. Din acest motiv, ar trebui să evitați alimentația frecventă cu hamburgeri și cartofi prăjiți: de fapt, după ce mâncați alimente prăjite și nesănătoase, o anumită cantitate de colesterol este depusă în celulele sanguine, crescând în timp.',
'52' => 'Vă rugăm să ne spuneți secretul dvs. de curățare a vaselor de sânge.',
'53' => 'Cu o utilizare regulată, CardioActive curăță chiar și cele mai înfundate vase de sânge în doar 1-2 săptămâni.',
'54' => 'Acest produs nu conține substanțe chimice. Acest preparat este un produs 100% natural și conține extrase medicinale rare de ierburi și fructe de pădure: păducel, fructe de hamei, coacăze, sunătoare, tei și coada de cal. De aceea este atât de benefic pentru organism.',
'55' => 'Majoritatea pacienților continuă să îmi ceară părerea cu privire la curățarea vaselor de sânge. Recent, le recomand doar acest produs: este foarte eficient.',
'56' => 'Rezultatele testului',
'57' => 'Normalizarea tensiunii arteriale la 1-2 zile după administrarea medicamentului - 99% dintre pacienți',
'58' => 'Normalizarea ritmului cardiac după tratament - 97% dintre pacienți',
'59' => 'Curățarea completă a vaselor de sânge de colesterol după tratament - 99% dintre pacienți',
'60' => 'Îmbunătățirea eficacității tratamentului bolilor cronice - 99% dintre pacienți',
'61' => 'Îmbunătățirea bunăstării totale - 100% dintre pacienți',
'62' => 'Absența oricărei reacții adverse în timpul tratamentului - 100% dintre pacienți',
'63' => 'Ne puteți spune mai multe despre cum să comandăm livrarea la domiciliu CardioActive la nivel național',
'64' => 'Pentru a comanda CardioActive',
'65' => 'După aceea, un manager te va contacta pentru a confirma adresa de livrare;',
'66' => 'Pentru a menține curățenia vaselor de sânge, recomand repetarea tratamentului la fiecare 1-2 ani, în special pentru persoanele în vârstă. Aceasta vă va ajuta să vă îmbunătățiți sănătatea și să întârziați apariția semnelor îmbătrânirii. A avea vase de sânge curate este o garanție a sănătății.',
'67' => 'Dr. Rossi, mulțumim pentru interviu și pentru furnizarea de informații importante.',
'68' => 'Stingând microfoanele, dr. Rossi a recunoscut că îi place să lucreze în grădină și să-și ajute copiii care au împlinit deja vârsta de pensionare. Soția sa este și ea o femeie de lungă durată: are 99 de ani. Soții curăță regulat vasele de sânge și încearcă să ducă un stil de viață activ. Profesorul consideră că acesta este singurul lucru care le susține viața.',
'69' => 'ACTUALIZARE DE LA',
'70' => 'Important',
'71' => 'Nume',
'72' => 'Număr de telefon',
'73' => 'TRIMITE O SOLICITARE',
'74' => 'Recepția cererilor se încheie',
'75' => 'Datele dvs. sunt trimise direct producătorului. Nimeni altcineva nu va avea acces la ele.',
'76' => 'Comentarii ',
'77' => 'Adelina',
'78' => 'Brașov',
'79' => 'Mihai',
'80' => 'Covasna',
'81' => 'Ciprian',
'82' => 'Timișoara',
'83' => 'Laura',
'84' => 'Suceava',
'85' => 'Mulțumesc, am comandat! Îmi place că medicamentul este complet natural și nu are efecte secundare!',
'86' => 'Marius',
'87' => 'București',
'88' => 'Pachetul a sosit ieri. Totul bine! Vă mulțumim! Am început să mă simt groaznic, sper că acest medicament vă va ajuta! A ajutat prietenului meu.',
'89' => 'Oana',
'90' => 'Constanța',
'91' => 'Horea',
'92' => 'Iași',
'93' => 'Am 61 de ani, iar acum 5 ani am început să îmi tratez vasele de sânge. CardioActive mă ajută să îmi mențin sănătatea și îmi dă putere. Mă simt absolut bine, iar mulți dintre colegii mei sunt deja morți. Nu mai vorbim de faptul că tot mai fac sex! Curățarea vaselor de sânge este necesară 100%!',
'94' => 'Nina',
'95' => 'Drobeta Turnu Severin',
'96' => 'Roberta',
'97' => 'Vaslui',
'98' => 'Vă mulțumim! Am văzut un program TV despre acest produs și toți medicii l-au recomandat. Ei au spus că curățarea vaselor este absolut necesară pentru toată lumea.',
'99' => 'Valeriu',
'100' => 'Mangalia',
'101' => 'Acest instrument este foarte eficient, confirm! Am avut 140/90 mulți ani, dar după tratament presiunea a revenit la 125/80. Mă simt excelent! ',
'102' => 'Ofelia',
'103' => 'Coman',
'104' => 'Silviu',
'105' => 'Cluj',
'106' => 'Am reușit să profit de reducere! Vă mulțumim!',
'107' => 'Petru',
'108' => 'Ploiești',
'109' => 'Am urmat un curs de tratament lunar (intermitent) și acum mă simt mai bine. Sunt plin de putere și energie, mi-am întărit sistemul imunitar. Mă simt mai tânăr cu 10-15 ani și am 72 de ani.',
'110' => 'Liliana',
'111' => 'Oradea',
'112' => 'Comandați CardioActive cu 50% reducere',
'113' => 'confidențialitate',
],
'block' => [
'b0' => [
'0' => 'Dr. Rossi spune că ',
'1' => 'secretul longevității constă în vasele de sânge',
'2' => 'dacă sunt sănătoase și curate, atunci puteți trăi până la 120 de ani și chiar mai mult, simțindu-vă absolut sănătos. Dr. Rossi este pe deplin încrezut în această afirmație.',
],
'b1' => [
'0' => 'Ce înseamnă să ai vase de sânge murdare? Imaginează-ți o țeavă plină de rugină. Ce se întâmplă? Presiunea apei crește, iar apa are un gust neplăcut. Același lucru se întâmplă și cu vasele de sânge: când colesterolul sau alte substanțe se instalează pe ele, presiunea crește ( ',
'1' => 'vasele murdare sunt cauza principală a hipertensiunii! ',
'2' => '), Sângele este umplut cu impurități, iar circulația sângelui este perturbată, ca urmare, apar modificări în toate organele și sistemele organismului, chiar și în piele.',
],
'b2' => [
'0' => 'Până de curând, procesul de purificare a celulelor sanguine a durat câteva luni. Eu am colectat plante medicinale, le-am căutat pe piață sau le-am comandat pe internet și le-am folosit pentru a face extracte acasă. Acum nu mai trebuie să fac toate acestea, deoarece colegii mei de la Institutul de Boli Cardiovasculare au creat un mijloc fiabil și ieftin pentru curățarea vaselor de sânge: ',
'1' => 'CardioActive',
'2' => '. Acest produs reglează tensiunea arterială și tratează hipertensiunea prin curățarea vaselor de sânge. Prin urmare, este excelent pentru scopurile noastre.',
],
'b3' => [
'0' => 'Statisticile oficiale ale studiilor clinice au fost prezentate pe site-ul Institutului de Boli Cardiovasculare, la care au participat aproximativ 2.000 de pacienți care au fost tratați cu ajutorul lui ',
'1' => 'CardioActive',
],
'b4' => [
'0' => 'Cât costă',
'1' => 'CardioActive',
'2' => 'i  șde unde se poate cumpăra?',
],
'b5' => [
'0' => 'După cum știți, pensionarea nu vă permite să cumpărați un medicament scump, așa că nu mi-aș permite să recomand un medicament scump pacienților și prietenilor mei.',
'1' => 'CardioActive',
'2' => 'nu este scump, dar acum este și cu o reducere mare până la',
],
'b6' => [
'0' => 'CardioActive',
'1' => 'cel mai bun preparat pentru combaterea hipertensiunii arteriale, pe care acum oricine îl poate cumpăra cu o reducere de 50%.',
],
'b7' => [
'0' => 'Completați ',
'1' => 'formularul de comandă',
],
'b8' => [
'0' => 'Poți obține',
'1' => 'CardioActive',
'2' => 'la cel mai apropiat oficiu poștal în 4-7 zile',
],
'b9' => [
'0' => 'Datorită numărului mare de solicitări, trebuie să limităm durata acestei campanii! Oferta va fi valabilă până la ',
'1' => 'inclusiv!',
'2' => 'Toate produsele noastre respectă principalele standarde europene de calitate și sunt verificate cu atenție înainte de expediere. Din motive de siguranță, toate pachetele sunt dezinfectate și abia atunci sunt trimise destinatarului. Toate manipulările cu produse se efectuează în costume speciale de protecție. Respectăm toate cerințele Ministerului Sănătății.',
],
'b10' => [
'0' => 'Formular de cerere oficial ',
'1' => 'N. 29 982 din 30.000 din ',
'2' => 'Comandați CardioActive la un preț promoțional',
'3' => 'Pentru a primi „CardioActive”, scrieți-vă numele și numărul de telefon în câmpurile de mai jos și faceți clic pe butonul „Trimite cererea”',
],
'b11' => [
'0' => 'Mulțumesc pentru articol, este foarte interesant. Am comandat deja ',
'1' => 'CardioActive',
],
'b12' => [
'0' => 'Am cumpărat și încercat deja CardioActive. Am suferit de hipertensiune arterială timp de 7 ani și nu-mi amintesc când totul a fost bine cu mine. La recomandarea unui medic, am decis să-mi curățez vasele de sânge. După o lună de tratament cu ',
'1' => 'CardioActive',
'2' => 'tensiunea mea a revenit la normal! Acum mă simt bine și durerile constante au trecut! Aceasta este o viață complet diferită: mă simt de o mie de ori mai bine. Recomand acest remediu excelent tuturor. Cu o astfel de reducere, este practic degeaba! ',
],
'b13' => [
'0' => 'A trecut o lună de tratament cu ',
'1' => 'CardioActive',
'2' => '. Mă simt mai sănătos și mai puternic. De parcă sunt cu 10 ani mai tânăr!',
],
'b14' => [
'0' => 'Acum o lună am început tratamentul cu ',
'1' => 'CardioActive',
'2' => '. Uneori, tensiunea arterială îmi creștea și nici nu puteam spăla vasele. Tinitusul și lipsa respirației mă înnebuneau .... Acum totul a revenit la normal și eram gata să plătesc 50000 de RON pentru sănătatea mea, dar mulțumesc Domnului că nu a trebuit! Medicamentul este foarte ieftin și ajută! Aceasta este o minune! Acum mă simt complet sănătoasă și plină de forță.',
],
'b15' => [
'0' => 'Datorită acestui medicament, mi-am vindecat hipertensiunea arterială, de care am suferit mulți ani. În timp, am fost diagnosticată cu diabet și am avut probleme cu rinichii, memoria și vederea. Mă tratam cât și cum am putut, am făcut proceduri scumpe, care nu au dat nici un rezultat și atunci am decis să încerc',
'1' => 'CardioActive',
'2' => '. Aceasta a fost prima dată când am comandat un medicament pe Internet, dar a fost foarte simplu. Vă mulțumim!',
],
'b16' => [
'0' => 'Am citit toate informațiile despre ',
'1' => 'CardioActive',
'2' => 'în internet! Bun remediu și eficient! Am băut eu câteva cursuri și mă simt grozav.',
],
'b17' => [
'0' => 'Am luat și eu un curs',
'1' => 'CardioActive',
'2' => '2 luni în urmă. Când a început să mă simtă rău, eram constant obosită și letargică, a apărut lipsa de respirație. Și acum am multă energie. Pot face mai multe treburi gospodărești în timpul zilei. Durerile de cap și crampele musculare au trecut. Și dorm mai bine. Voi recomanda acest remediu prietenilor și colegilor!',
],
],
];
